config/routes.rb
Rails.application.routes.draw do

  resources :tours
  resources :tour_reservations
  resources :group_tour_reservations

  root 'tours#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group_tour_reservation.rb
class GroupTourReservation < ApplicationRecord
  has_many :tour_reservations, dependent: :nullify
  accepts_nested_attributes_for :tour_reservations,
                                reject_if: lambda { |attr| attr['id'].blank? }

  attribute :date, :datetime, default: DateTime.now

  validates_presence_of :name

end

app/models/tour.rb
class Tour < ApplicationRecord
  has_many :tour_reservations

  attribute :ad_price, :decimal, default: 0.00
  attribute :ch_price, :decimal, default: 0.00
  attribute :add_ad_price, :decimal, default: 0.00
  attribute :add_ch_price, :decimal, default: 0.00
  attribute :add_chg, :decimal, default: 0.00

  validates :name, presence: true, length: { in: 3..65 }
  validates :ad_price, presence: true, numericality: { greater_than_or_equal_to: 0.01 }
  validates :ch_price, presence: true, numericality: { greater_than_or_equal_to: 0.00 }
  validates :add_ad_price, presence: true, numericality: { greater_than_or_equal_to: 0.00 }
  validates :add_ch_price, presence: true, numericality: { greater_than_or_equal_to: 0.00 }
  validates :add_chg, presence: true, numericality: { greater_than_or_equal_to: 0.00 }
  validates_length_of :description, maximum: 660
end

app/models/tour_reservation.rb
class TourReservation < ApplicationRecord

  belongs_to :tour
  belongs_to :group_tour_reservation, optional: true

  after_initialize :set_defaults


  validates :voucher, length: { in: 2..20 }
  validates :ad_sale_price, presence: true, numericality: { greater_than_or_equal_to: 0.01}
  validates :add_ad_sale_price, presence: true, numericality: { greater_than_or_equal_to: 0.0}
  validates :ch_sale_price, presence: true, numericality: { greater_than_or_equal_to: 0.0}
  validates :add_ch_sale_price, presence: true, numericality: { greater_than_or_equal_to: 0.0}
  validates :add_chg_sale_price, presence: true, numericality: { greater_than_or_equal_to: 0.0}
  validates :pax_ad, presence: true, numericality: { greater_than_or_equal_to: 1}
  validates :pax_add_ad, presence: true, numericality: { greater_than_or_equal_to: 0}
  validates :pax_ch, presence: true, numericality: { greater_than_or_equal_to: 0}
  validates :pax_add_ch, presence: true, numericality: { greater_than_or_equal_to: 0}
  validates :pax_add_chg, presence: true, numericality: { greater_than_or_equal_to: 0}

  def set_defaults
    self.voucher            ||= "00000"
    self.ad_sale_price      ||= 0.00
    self.add_ad_sale_price  ||= 0.00
    self.ch_sale_price      ||= 0.00
    self.add_ch_sale_price  ||= 0.00
    self.add_chg_sale_price ||= 0.00
    self.pax_ad             ||= 0
    self.pax_add_ad         ||= 0
    self.pax_ch             ||= 0
    self.pax_add_ch         ||= 0
    self.pax_add_chg        ||= 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/group_tour_reservations_controller.rb
class GroupTourReservationsController < ApplicationController
  before_action :find_group_reservation, only: [:edit, :show, :update, :destroy]

  def index
    respond_to do |format|
      format.html { @group_tour_reservations = GroupTourReservation.order("date ASC").page(params[:page])}
      format.json { @group_tour_reservations }
    end
  end

  def show

  end

  def new
    @group_tour_reservation = params[:selected_date].blank? ? GroupTourReservation.new :
                              GroupTourReservation.new(date: params[:selected_date])
  end

  def create
    @group_tour_reservation = GroupTourReservation.new(group_tour_reservation_params)

    respond_to do |format|
      if @group_tour_reservation.save
        format.html { redirect_to @group_tour_reservation }
        format.js
      elsif
        format.html { render 'new' }
        #byebug
        format.js
      end
    end
  end

  ## GET
  def edit
  end
  #POST
  def update

    respond_to do |format|
      if @group_tour_reservation.update(group_tour_reservation_params)
        format.html { redirect_to edit_group_tour_reservation_path(@group_tour_reservation) }
        format.js
      else
        format.html { render 'edit' }
        format.js
      end
    end
  end

  def destroy
    @group_tour_reservation.destroy
    redirect_to group_tour_reservations_path, notice: 'Group Reservation was deleted'
  end

  private

  def group_tour_reservation_params
    params.require(:group_tour_reservation).permit(:name, :date, :guide, :guide_pay,
                                                   :vehicle, :vehicle_pay,
                                                   tour_reservation_ids: [])
  end

  def change_list_date
    @group_tour_reservation = params[:group_tour_reservation]
    render 'new'
  end

  def find_group_reservation
    @group_tour_reservation = GroupTourReservation.find(params[:id])
  end

end

app/controllers/tour_reservations_controller.rb
class TourReservationsController < ApplicationController
  before_action :find_tour_reservations, only: [:show, :edit, :update, :destroy]

  def index
    @t_reservations = TourReservation.order("date ASC").page(params[:page])
  end

  def show
  end

  def new
    @t_reservation = TourReservation.new
  end

  def create
    @t_reservation = TourReservation.new(tour_reservations_params)
    if @t_reservation.save
      redirect_to tour_reservations_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @t_reservation.update(tour_reservations_params)
      redirect_to tour_reservations_path
    else
      render 'edit'
    end
  end

  def destroy
    @t_reservation.destroy
    redirect_to tour_reservations_path
  end


  private

    def tour_reservations_params
      params.require(:tour_reservation).permit(:tour_id, :date, :hotel, :phone,
                                                               :ad_sale_price, :ch_sale_price,
                                                               :add_ad_sale_price, :add_ch_sale_price,
                                                               :add_chg_sale_price, :pax_ad, :pax_ch,
                                                               :pax_add_ad, :pax_add_ch, :pax_add_chg,
                                                               :agent, :guide, :voucher, :p_up_time)
    end

    def find_tour_reservations
        @t_reservation = TourReservation.find(params[:id])
    end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :find_tour, only: [:show, :edit, :update, :destroy]

  def index
    if params[:sort]
      @tours = Tour.order(params[:sort]).page(params[:page])
    else
      @tours = Tour.order("name ASC").page(params[:page])
    end
  end

  def show
  end

  def new
    @tour = Tour.new
  end

  def create
    @tour = Tour.new(tour_params)
    if @tour.save
      redirect_to tours_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @tour.update(tour_params)
      flash[:notice] = "Tour Updated"
      redirect_to tours_path
    else
      render 'edit'
    end
  end

  def destroy
    @tour.destroy
    redirect_to tours_path
  end

  private

    def find_tour
      @tour = Tour.find(params[:id])
    end

    def tour_params
      params.require(:tour).permit(:name, :ad_price, :ch_price, :add_ad_price,
                                          :add_ch_price, :add_chg, :description)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_tour_reservations_helper.rb
module GroupTourReservationsHelper
end

app/helpers/tour_reservations_helper.rb
module TourReservationsHelper

  def reservation_pax(reservation)
    adults = reservation.pax_ad + reservation.pax_add_ad
    content_tag(:small, "AD: #{adults}; CH: #{reservation.pax_ch}")
  end

end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/group_tour_reservations/_available_reservations.html.erb
 <%= form.collection_check_boxes(:tour_reservation_ids, TourReservation.where(group_tour_reservation_id: nil, date: @group_tour_reservation.date), :id, :id, include_hidden: false ) do |b| %>
    <tr>
      <td>
        <!-- Material unchecked -->
        <%= b.label(class: "form-check") do %>
          <%= b.check_box(class: "form-check-input") %>
          <%= b.object.tour.name %> </br>
          <%= reservation_pax(b.object) %>
        <% end %>
      </td>
      <td>
          <%= b.object.date.strftime("%B %d %Y") %>
      </td>
      <td>
          <%= b.object.voucher %>
      </td>
      <td>
          <%= b.object.phone %>
      </td>
      <td>
          <%= b.object.p_up_time.strftime("%I:%M %p") %>
      </td>
    </tr>
  <% end %>

app/views/group_tour_reservations/_error_messages.html.erb
<% if @group_tour_reservation.errors.any? %>
  <div class="alert alert-danger">
    <p>Please correct the following <%= pluralize(@group_tour_reservation.errors.count, "error") %>:</p>
    <ul>
      <% @group_tour_reservation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/group_tour_reservations/_form.html.erb

<%= form_with model: @group_tour_reservation, local: true do |form| %>
<form>
  <div class="form-row py-3">
    <div class="form-group col-md-4">
      <%= form.label :name, 'Group Name' %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group col-md-2">
      <%= form.label :date, 'Group Date' %>
      <%= form.date_field :date, class: 'form-control' %>
    </div>
  </div>
  <div class="form-row py-3">
    <div class="form-group col-md-3">
      <%= form.label :vehicle, 'Select Vehicle' %>
      <%= form.text_field :vehicle, class: 'form-control' %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :vehicle_pay, 'Vehicle Pay' %>
      <%= form.number_field :vehicle_pay, class: 'form-control' %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :guide, 'Select Guide' %>
      <%= form.text_field :guide, class: 'form-control' %>
    </div>
    <div class="form-group col-md-3">
      <%= form.label :guide_pay, 'Guide Pay' %>
      <%= form.number_field :guide_pay, class: 'form-control' %>
    </div>
  </div>

  <h4>SELECT RESERVATIONS TO GROUP</h5>
  <div class="form-row py-3">
    <!-- Table  -->
    <table id="tour_reservations" class="table table-bordered">
      <!-- Table head -->
      <thead>
        <tr>
          <th>TOUR</th>
          <th>DATE</th>
          <th>VOUCHER</th>
          <th>MOBILE</th>
          <th>PICK UP</th>
        </tr>
      </thead>
      <!-- Table head -->

      <!-- Table body -->
      <tbody >
        <%= render partial: 'available_reservations', locals: { form: form } %>
        </tr>
      </tbody>

      <!-- Table body -->
    </table>
    <!-- Table  -->
  </div>
  <%= link_to "Back to Group Reservations", group_tour_reservations_path, class: "btn btn-outline-secondary" %>
  <%= form.submit @group_tour_reservation.new_record? ? "Create Reservation" : "Save", class: "btn btn-success float-right" %>
</form>
<% end %>




app/views/group_tour_reservations/_group_tour_reservation.html.erb
<tr>
  <tbody>
    <td><%= group_tour_reservation.name %></td>
    <td><%= group_tour_reservation.date.strftime("%B %d %Y") %></td>
    <td><%= group_tour_reservation.guide %></td>
    <td>
      <%= number_to_currency(group_tour_reservation.guide_pay, unit: " THB", format: "%n%u") %>
    </td>
    <td><%= group_tour_reservation.vehicle %></td>
    <td>
      <%= number_to_currency(group_tour_reservation.vehicle_pay, unit: " THB", format: "%n%u") %>
    </td>
    <td>
      <div class="btn-group">
        <%= link_to "VIEW", group_tour_reservation, class: "btn btn-sm btn-outline-info" %>
        <%= link_to "EDIT", edit_group_tour_reservation_path(group_tour_reservation), class: "btn btn-sm btn-outline-primary" %>
        <%= link_to "DELETE", group_tour_reservation, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-outline-danger" %>
      </div>
    </td>
  </tbody>
</tr>

app/views/group_tour_reservations/create.html.erb
<h1>GroupTourReservations#create</h1>
<p>Find me in app/views/group_tour_reservations/create.html.erb</p>

app/views/group_tour_reservations/destroy.html.erb
<h1>GroupTourReservations#destroy</h1>
<p>Find me in app/views/group_tour_reservations/destroy.html.erb</p>

app/views/group_tour_reservations/edit.html.erb
<h3 class="text-center">Edit Group Reservation</h3>

<article>
  <%= render 'form', group_tour_reservation: @group_tour_reservation %>
</article>

app/views/group_tour_reservations/index.html.erb
<div class="row py-4">
  <div class="col">
    <h2>All Group Reservations</h2>
    <%= link_to "New Group Reservatons", new_group_tour_reservation_path, class: "btn btn-primary" %>
    <hr />
    <table class="table">
      <tr>
        <thead>
          <th>Name</th>
          <th>DATE</th>
          <th>GUIDE</th>
          <th>GUIDE PAY</th>
          <th>VEHICLE</th>
          <th>VEHICLE PAY</th>
          <th>Actions</th>
        </thead>
      </tr>
      <%= render @group_tour_reservations %>
    </table>

    <% if @group_tour_reservations.empty? %>
        <p>There are no <strong>Tours</strong> yet</p>
    <% end %>
  </div>
</div>

app/views/group_tour_reservations/new.html.erb
<h3>New Group Reservation</h3>

<%= render 'form', group_tour_reservation: @group_tour_reservation %>

app/views/group_tour_reservations/show.html.erb
<h1>GroupTourReservations#show</h1>
<p>Find me in app/views/group_tour_reservations/show.html.erb</p>

app/views/group_tour_reservations/update.html.erb
<h1>GroupTourReservations#update</h1>
<p>Find me in app/views/group_tour_reservations/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Angles</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">

      <%= render 'shared/nav' %>

      <%= yield %>

    </div>
  <%= javascript_pack_tag 'controllers/group_tour_reservation_controller', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown09" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">RESERVATIONS</a>
        <div class="dropdown-menu" aria-labelledby="dropdown09">
          <%= link_to "Tour Reservations", tour_reservations_path, class: "dropdown-item" %>
          <%= link_to "Group Reservations", group_tour_reservations_path, class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
  <strong><a class="navbar-brand mx-auto" href="/">ANGLES</a></strong>
  <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav ml-auto">
        <li class="nav-item">
            <%= link_to "TOURS", tours_path, class: 'nav-link' %>
        </li>
      </ul>
  </div>
</nav>

app/views/tour_reservations/_error_messages.html.erb
  <% if @t_reservation.errors.any? %>
    <div class="alert alert-danger">
      <p>Please correct the following <%= pluralize(@t_reservation.errors.count, "error") %>:</p>
      <ul>
        <% @t_reservation.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/tour_reservations/_form.html.erb
  <%= render 'error_messages' %>

  <%= form_with model: @t_reservation, local: true do |f| %>
    <form>
      <div class="row">
        <div class="col">
        <%= f.label :tour_id, "Select Tour" %>
        <%= f.collection_select(:tour_id, Tour.all.order("name ASC"), :id, :name, { selected: Tour.first }, { class: "form-control"}) %>
        </div>
        <div class="col">
        <%= f.label :date, "Select Date" %>
        <%= f.date_field :date, class: "form-control" %>
        </div>
        <div class="col">
          <%= f.label :phone, "Phone Number" %>
          <%= f.text_field :phone, placeholder: "+66 666 666666", class: "form-control" %>
        </div>
        <div class="col">
          <%= f.label :voucher, "Voucher" %>
          <%= f.text_field :voucher, class: "form-control" %>
        </div>
        <div class="col">
          <%= f.label :agent, "Agent" %>
          <%= f.text_field :agent, class: "form-control" %>
        </div>
        <div class="col">
          <%= f.label :guide, "GUIDE" %>
          <%= f.text_field :guide, class: "form-control" %>
        </div>
      </div>
      <br />
      <div class="row">
        <div class="col">
        <%= f.label :hotel, "Hotel Name" %>
        <%= f.text_field :hotel, placeholder: "Select Hotel", class: "form-control" %>
        </div>
        <div class="col">
        <%= f.label :p_up_time, "Pick up" %>
        <%= f.time_field :p_up_time, class: "form-control" %>
        </div>
      </div>

      <hr />

      <div class="row">
        <div class="col">
          <%= f.label :ad_sale_price, "SALE AD 1" %>
          <%= f.number_field :ad_sale_price, class: "form-control" %>
        </div>
        <div class="col">
          <%= f.label :add_ad_sale_price, "SALE AD 2" %>
          <%= f.number_field :add_ad_sale_price, class: "form-control" %>
        </div>
        <div class="col">
          <%= f.label :ch_sale_price, "SALE CH 1" %>
          <%= f.number_field :ch_sale_price, class: "form-control" %>
        </div>
        <div class="col">
          <%= f.label :add_ch_sale_price, "SALE CH 2" %>
          <%= f.number_field :add_ch_sale_price, class: "form-control" %>
        </div>
        <div class="col">
          <%= f.label :add_chg_sale_price, "SALE ADD CHG" %>
          <%= f.number_field :add_chg_sale_price, class: "form-control" %>
        </div>
      </div>
      <br />
      <div class="row">
        <div class="col">
          <%= f.label :pax_ad, "PAX AD 1" %>
          <%= f.number_field :pax_ad, class: "form-control" %>
        </div>
        <div class="col">
          <%= f.label :pax_add_ad, "PAX AD 2" %>
          <%= f.number_field :pax_add_ad, class: "form-control" %>
        </div>
        <div class="col">
          <%= f.label :pax_ch, "PAX CH 1" %>
          <%= f.number_field :pax_ch, class: "form-control" %>
        </div>
        <div class="col">
          <%= f.label :pax_add_ch, "PAX CH 2" %>
          <%= f.number_field :pax_add_ch, class: "form-control" %>
        </div>
        <div class="col">
          <%= f.label :pax_add_chg, "PAX ADD CHG" %>
          <%= f.number_field :pax_add_chg, class: "form-control" %>
        </div>
      </div>
      <br />
      <div class="row">
        <div class="col">
          <%= link_to "Back to Tour Reservations", tour_reservations_path, class: "btn btn-outline-secondary" %>
          <%= f.submit @t_reservation.new_record? ? "Create Reservation" : "Update Reservation", class: "btn btn-success float-right" %>
        </div>
      </div>
    </form>
  <% end %>

app/views/tour_reservations/_tour_reservation.html.erb
<tr>
  <tbody>
    <td><%= tour_reservation.date.strftime("%B %d %Y") %></td>
    <td><%= tour_reservation.tour.name %></td>
    <td><%= tour_reservation.hotel %></td>
    <td><%= tour_reservation.p_up_time.strftime("%I:%M %p") %></td>
    <td><%= tour_reservation.voucher %></td>
    <td><%= tour_reservation.phone %></td>
    <td><%= tour_reservation.agent %></td>
    <td>
      <div class="btn-group">
      <%= link_to "VIEW", tour_reservation, class: "btn btn-sm btn-outline-info" %>
      <%= link_to "EDIT", edit_tour_reservation_path(tour_reservation), class: "btn btn-sm btn-outline-primary" %>
      <%= link_to "DELETE", tour_reservation, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-outline-danger" %>
      </div>
    </td>
  </tbody>
</tr>

app/views/tour_reservations/create.html.erb
<h1>TourReservations#create</h1>
<p>Find me in app/views/tour_reservations/create.html.erb</p>

app/views/tour_reservations/destroy.html.erb
<h1>TourReservations#destroy</h1>
<p>Find me in app/views/tour_reservations/destroy.html.erb</p>

app/views/tour_reservations/edit.html.erb
<h3>Edit Tour Reservations</h3>
<%= link_to "View Reservation", @t_reservation, class: "btn btn-info" %>
<hr />

<article>
  <%= render 'form' %>
</article>

app/views/tour_reservations/index.html.erb
<div class="row py-4">
  <div class="col">
    <h2>Tour Reservations</h2>
    <%= link_to "New Tour Reservation", new_tour_reservation_path, class: "btn btn-primary mb-3" %>
    <hr />
    <%= paginate @t_reservations %>

    <table class="table">
      <tr>
        <thead>
          <th>DATE</th>
          <th>TOUR</th>
          <th>HOTEL</th>
          <th>PICK UP</th>
          <th>VOUCHER</th>
          <th>MOBILE</th>
          <th>AGENT</th>
          <th>ACTIONS</th>
        </thead>
      </tr>
      <%= render @t_reservations %>
    </table>

    <% if @t_reservations.empty? %>
        <p>There are no <strong>Tour Reservations</strong> yet</p>
    <% end %>

    <%= paginate @t_reservations %>
  </div>
</div>

app/views/tour_reservations/new.html.erb
<h1>New Tour Reservation</h1>

<%= render 'form' %>

app/views/tour_reservations/show.html.erb
</br>
<h4><%= @t_reservation.tour.name %> Reservation |
<%= @t_reservation.date.strftime("%B %d %Y") %></h4>
<h6>Voucher: <%= @t_reservation.voucher %> | <%= @t_reservation.agent %> |
  <%= @t_reservation.guide %></h6>
<div class="row">
  <div class="col-md-12">
    <table class="table">
      <tr>
        <thead>
          <th>PICK UP: </th>
          <th>HOTEL: </th>
          <th>SALE AD 1</th>
          <th>SALE AD 2</th>
          <th>SALE CH 1</th>
          <th>SALE CH 2</th>
          <th>SALE ADD CHG</th>
        </thead>
      </tr>
      <tr>
        <tbody>
          <td><%= @t_reservation.p_up_time.strftime("%I:%M %p") %></td>
          <td><%= @t_reservation.hotel %></td>
          <td><%= number_to_currency(@t_reservation.ad_sale_price, unit: " THB", format: "%n%u") %></td>
          <td><%= number_to_currency(@t_reservation.add_ad_sale_price, unit: " THB", format: "%n%u") %></td>
          <td><%= number_to_currency(@t_reservation.ch_sale_price, unit: " THB", format: "%n%u") %></td>
          <td><%=number_to_currency(@t_reservation.add_ch_sale_price, unit: " THB", format: "%n%u") %></td>
          <td><%= number_to_currency(@t_reservation.add_chg_sale_price, unit: " THB", format: "%n%u") %></td>
        </tbody>
      </tr>
    </table>
    <div>
      <p>Customer Number: <%= @t_reservation.phone %></p>
      <div>
        <%= link_to "Back to Reservations", tour_reservations_path, class: "btn btn-sm btn-outline-secondary" %>
        <div class="btn-group mb-3 float-right">
          <%= link_to "Edit Reservation", edit_tour_reservation_path(@t_reservation), class: "btn btn-sm btn-primary" %>
          <%= link_to "Delete Reservation", @t_reservation, method: :delete, data: { confirm: "Are you sure you want to delete this Reservation Record?"}, class: "btn btn-sm  btn-danger" %>
        </div>
      </div>
    </div>
  </div>

  <div class="col">
    <h4 class="text-center">PROFIT</h4>
    <table class="table">
      <tr>
        <thead class="thead-light">
          <th>COSTING</th>
          <th>SELLING</th>
          <th>TOTAL PROFIT</th>
        </thead>
      </tr>
      <tr>
        <td><%= number_to_currency(@costing, unit: " THB", format: "%n%u") %></td>
        <td><%= number_to_currency(@selling, unit: " THB", format: "%n%u") %></td>
        <td><%= number_to_currency(@profit, unit: " THB", format: "%n%u") %></td>
      </tr>
    </table>
  </div>
</div>

app/views/tour_reservations/update.html.erb
<h1>TourReservations#update</h1>
<p>Find me in app/views/tour_reservations/update.html.erb</p>

app/views/tours/_error_messages.html.erb
  <% if @tour.errors.any? %>
    <div class="alert alert-danger">
      <p>Please correct the following <%= pluralize(@tour.errors.count, "error") %>:</p>
      <ul>
        <% @tour.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/tours/_tour.html.erb

<tr>
  <tbody>
    <td><%= tour.name %></td>
    <td><%= number_to_currency(tour.ad_price, unit: " THB", format: "%n%u") %></td>
    <td><%= number_to_currency(tour.ch_price, unit: " THB", format: "%n%u") %></td>
    <td><%= number_to_currency(tour.add_ad_price, unit: " THB", format: "%n%u") %></td>
    <td><%= number_to_currency(tour.add_ch_price, unit: " THB", format: "%n%u") %></td>
    <td><%= number_to_currency(tour.add_chg, unit: " THB", format: "%n%u") %></td>
    <td>
      <div class="btn-group">
        <%= link_to "Edit", edit_tour_path(tour), class: "btn btn-outline-primary" %>
        <%= link_to "Delete", tour, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
      </div>
    </td>
  </tbody>
</tr>


app/views/tours/create.html.erb
<h1>Tours#create</h1>
<p>Find me in app/views/tours/create.html.erb</p>

app/views/tours/destroy.html.erb
<h1>Tours#destroy</h1>
<p>Find me in app/views/tours/destroy.html.erb</p>

app/views/tours/index.html.erb
<div class="row">
  <div class="col">
    <h1 class="text-center">All Tours</h1>
    <hr />
    <%= link_to "New Tour", new_tour_path, class: "btn  btn-primary mb-3 btn-block" %>
    <table class="table">
      <%= paginate @tours %>
      <tr>
        <thead>
          <th>Name <%= link_to "sort", tours_path(sort: "name") %></th>
          <th>AD 1 <%= link_to "sort", tours_path(sort: "ad_price") %></th>
          <th>CH 1 <%= link_to "sort", tours_path(sort: "ch_price") %></th>
          <th>AD 2 <%= link_to "sort", tours_path(sort: "add_ad_price") %></th>
          <th>CH 2 <%= link_to "sort", tours_path(sort: "add_ch_price") %></th>
          <th>ADD CHG <%= link_to "sort", tours_path(sort: "add_chg") %></th>
          <th>Actions</th>
        </thead>
      </tr>
      <%= render @tours %>
    </table>

    <% if @tours.empty? %>
        <p>There are no <strong>Tours</strong> yet</p>
    <% end %>

    <%= paginate @tours %>
  </div>
</div>
<br />